language: cpp
os:
  - linux
  - osx

sudo: true

env:
  matrix:
   - DBGTOOLS_CONFIG=debug
   - DBGTOOLS_CONFIG=release

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update -qq
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install linux-headers-$(uname -r)

compiler:
  - gcc
  - clang

install:
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - ./make_unix.sh
  - cd ..

script:
  - bam/bam compiler=$CC config=$DBGTOOLS_CONFIG
  - local/$DBGTOOLS_CONFIG/linux_x86_64/test_assert
  - local/$DBGTOOLS_CONFIG/linux_x86_64/test_callstack
  - local/$DBGTOOLS_CONFIG/linux_x86_64/test_callstack_cpp
