platform:
  - x86

configuration:
  - Debug
  - Release

install:
  - c:\"Program Files (x86)"\"Microsoft Visual Studio 12.0"\VC\vcvarsall.bat
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - make_win64_msvc.bat
  - cd ..
  - bam\bam.exe

build: OFF
test: OFF
test_script: OFF
deploy: OFF
